// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationParonAB.Data;

#nullable disable

namespace WebApplicationParonAB.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FardigvarulagerProdukter", b =>
                {
                    b.Property<int>("FardigvarulagerLagernr")
                        .HasColumnType("int");

                    b.Property<string>("ProdukterProduktnr")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FardigvarulagerLagernr", "ProdukterProduktnr");

                    b.HasIndex("ProdukterProduktnr");

                    b.ToTable("FardigvarulagerProdukter");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Fardigvarulager", b =>
                {
                    b.Property<int>("Lagernr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lagernr"));

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Lagernr");

                    b.HasIndex("Stad")
                        .IsUnique();

                    b.ToTable("Fardigvarulager");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.InOchUtLeverans", b =>
                {
                    b.Property<int>("Leveransnr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Leveransnr"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FardigvarulagerLagernr")
                        .HasColumnType("int");

                    b.Property<string>("Produkt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProdukterProduktnr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Till_eller_fran")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Leveransnr");

                    b.HasIndex("FardigvarulagerLagernr");

                    b.HasIndex("ProdukterProduktnr");

                    b.ToTable("InOchUtLeverans");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Lagersaldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fardigvarulager")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FardigvarulagerLagernr")
                        .HasColumnType("int");

                    b.Property<string>("Produkt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProduktrefProduktnr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.Property<int>("UniqueIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FardigvarulagerLagernr");

                    b.HasIndex("ProduktrefProduktnr");

                    b.HasIndex("Produkt", "Fardigvarulager")
                        .IsUnique();

                    b.ToTable("Lagersaldo");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Produkter", b =>
                {
                    b.Property<string>("Produktnr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Benamning")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Pris")
                        .HasColumnType("int");

                    b.HasKey("Produktnr");

                    b.HasIndex("Benamning")
                        .IsUnique();

                    b.ToTable("Produkter");

                    b.HasData(
                        new
                        {
                            Produktnr = "P001",
                            Benamning = "jTelefon",
                            Pris = 6000
                        },
                        new
                        {
                            Produktnr = "P002",
                            Benamning = "jPlatta",
                            Pris = 8000
                        },
                        new
                        {
                            Produktnr = "P003",
                            Benamning = "Päronklocka",
                            Pris = 12000
                        });
                });

            modelBuilder.Entity("FardigvarulagerProdukter", b =>
                {
                    b.HasOne("WebApplicationParonAB.Models.Fardigvarulager", null)
                        .WithMany()
                        .HasForeignKey("FardigvarulagerLagernr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationParonAB.Models.Produkter", null)
                        .WithMany()
                        .HasForeignKey("ProdukterProduktnr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.InOchUtLeverans", b =>
                {
                    b.HasOne("WebApplicationParonAB.Models.Fardigvarulager", null)
                        .WithMany("InOchUtLeverans")
                        .HasForeignKey("FardigvarulagerLagernr");

                    b.HasOne("WebApplicationParonAB.Models.Produkter", null)
                        .WithMany("InOchUtLeverans")
                        .HasForeignKey("ProdukterProduktnr");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Lagersaldo", b =>
                {
                    b.HasOne("WebApplicationParonAB.Models.Fardigvarulager", null)
                        .WithMany("Lagersaldo")
                        .HasForeignKey("FardigvarulagerLagernr");

                    b.HasOne("WebApplicationParonAB.Models.Produkter", "Produktref")
                        .WithMany("Lagersaldo")
                        .HasForeignKey("ProduktrefProduktnr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produktref");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Fardigvarulager", b =>
                {
                    b.Navigation("InOchUtLeverans");

                    b.Navigation("Lagersaldo");
                });

            modelBuilder.Entity("WebApplicationParonAB.Models.Produkter", b =>
                {
                    b.Navigation("InOchUtLeverans");

                    b.Navigation("Lagersaldo");
                });
#pragma warning restore 612, 618
        }
    }
}
